---
kind: pipeline
type: docker
name: default

steps:
- name: validate
  image: hashcorp/packer:1.5.6
  environment:
    AWS_ACCESS_KEY:
      from_secret: AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION
  commands:
    - packer validate -syntax-only packer.json

- name: build
  image: hashcorp/packer:1.5.6
  environment:
    AWS_ACCESS_KEY:
      from_secret: AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:
      from_secret: AWS_DEFAULT_REGION
  commands:
    - apk --no-cache add ansible
    - packer build packer.json

volumes:
  - name: cache
    temp: {}

